name: test
on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    #needs: push_to_registry
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: t-shiotani/alibabamanifest
